### ISSUE TITLE
Merged into loaders.gl

### ISSUE THREAD

**Issue by ibgreen** [nopor/loaders.gl-compiler-issue#1]
Thanks for setting this up! 

This is being merged into loaders.gl to help resolve the issue. See https://github.com/visgl/loaders.gl/pull/1908.

Adding an open source `LICENSE` file (e.g. MIT) in this repo would be appreciated, to clear out any concerns with the merge.

**Comment by nopor** [comment]
Thank you.
Added a license file (MIT).
